#!/bin/bash
FILE=./RUNNER_TOKEN
if [ -f "$FILE" ]; then
    RUNNER_TOKEN=$(<$FILE)
else 
    echo "Runner Token file does not exist!"
    exit 1
fi

# Static Files. Make sure they're present in your Resources folder
IMAGE_LABELS=$(<./IMAGE_LABELS)
# Files generated by Cilicon
RUNNER_NAME=$(<./RUNNER_NAME)
RUNNER_LABELS=$(<./RUNNER_LABELS)
RUNNER_DOWNLOAD_URL=$(<./RUNNER_DOWNLOAD_URL)

curl -o actions-runner.tar.gz -L $RUNNER_DOWNLOAD_URL

# Create a folder
mkdir ~/actions-runner
# Extract the installer
tar xzf ./actions-runner.tar.gz --directory ~/actions-runner

cp pre-run.sh ~/actions-runner
cp post-run.sh ~/actions-runner

cd ~/actions-runner

export ACTIONS_RUNNER_HOOK_JOB_STARTED=~/actions-runner/pre-run.sh
export ACTIONS_RUNNER_HOOK_JOB_COMPLETED=~/actions-runner/post-run.sh

# Create the runner and start the configuration experience
ALL_LABELS="${IMAGE_LABELS},${RUNNER_LABELS}"
./config.sh --url https://github.com/traderepublic --ephemeral --replace --labels $ALL_LABELS --name $RUNNER_NAME --runnergroup mac-ci --work _work --token $RUNNER_TOKEN

# Last step, run it!
./run.sh
